namespace Managers.Audio_Manager
{
    public enum AudioTypes
    {
        None =0,
        MainMusic = 1,
        Button = 2,
        Chain = 3,
        Jump = 4,
        Laser = 5,
        Paper = 6,
        Vacuum = 7,
        Land = 8,
        Dash = 9,
        Poof = 10,
        Feesh =11,
        PossesIn=12,
        PossesOut=13,
        Walk=14,
        MagnetActivate=15,
        BalloonActivate=16,
        MetalImpact=17,
        PaperImpact=18,
        SoulShardCollect=19,
        ButtonClicked=20,
        Die=21,
        AxeSlash =22,
        BombExplosion=23,
        BombThrow=24,
        Charging=25,
        FireballThrow=26,
        LandingImpact=27,
        LandingImpact2=28,
        Lose=29,
        RollingDice=30,
        ShurikenImpact=31,
        ShurikenThrow=32,
        Slicing=33,
        SwordSound=34,
        Ticktack=35,
        Win=36,
        StreetLove=37,
        StupidDancer=38,
        Fight=39,
        GameOver=40,
        KillHim=41,
        Number1=42,
        Number2=43,
        Number3=44,
        PrepareYourself=45,
        Ready=46,
        YouLose=47,
        YouWin=48,

    }
}